language: php

php:
  - 5.6
  - nightly


sudo: false

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - ./bin/phpunit
  - xmllint --noout --schema phpunit.xsd phpunit.xml

notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: false
