language: php

php:
  - 5.6
  - nightly


sudo: false

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - ./phpunit
  - ./phpunit --configuration ./phpunit.xml > /dev/null; if [ $? -eq 0 ]; then echo "SHOULD FAIL"; false; else echo "fail checked"; fi;
  - xmllint --noout --schema phpunit.xsd phpunit.xml

notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: false
