<?php

namespace manrog\classes\util;

/**
 * Class Php
 *
 * Wraps php functions, for better testing and upgrade compatibility.
 *
 * !!! NOT USE, IF YOU NOT NEED. PERFORMANCE IMPACT !!!
 *
 * Below only for IDE compatibility
 *
 * @package manrog
 *
 * @method zend_version
 * @method func_num_args
 * @method func_get_arg
 * @method func_get_args
 * @method strlen
 * @method strcmp
 * @method strncmp
 * @method strcasecmp
 * @method strncasecmp
 * @method each
 * @method error_reporting
 * @method define
 * @method defined
 * @method get_class
 * @method get_called_class
 * @method get_parent_class
 * @method method_exists
 * @method property_exists
 * @method class_exists
 * @method interface_exists
 * @method trait_exists
 * @method function_exists
 * @method class_alias
 * @method get_included_files
 * @method get_required_files
 * @method is_subclass_of
 * @method is_a
 * @method get_class_vars
 * @method get_object_vars
 * @method get_class_methods
 * @method trigger_error
 * @method user_error
 * @method set_error_handler
 * @method restore_error_handler
 * @method set_exception_handler
 * @method restore_exception_handler
 * @method get_declared_classes
 * @method get_declared_traits
 * @method get_declared_interfaces
 * @method get_defined_functions
 * @method get_defined_vars
 * @method create_function
 * @method get_resource_type
 * @method get_loaded_extensions
 * @method extension_loaded
 * @method get_extension_funcs
 * @method get_defined_constants
 * @method debug_backtrace
 * @method debug_print_backtrace
 * @method gc_collect_cycles
 * @method gc_enabled
 * @method gc_enable
 * @method gc_disable
 * @method strtotime
 * @method date
 * @method idate
 * @method gmdate
 * @method mktime
 * @method gmmktime
 * @method checkdate
 * @method strftime
 * @method gmstrftime
 * @method time
 * @method localtime
 * @method getdate
 * @method date_create
 * @method date_create_immutable
 * @method date_create_from_format
 * @method date_create_immutable_from_format
 * @method date_parse
 * @method date_parse_from_format
 * @method date_get_last_errors
 * @method date_format
 * @method date_modify
 * @method date_add
 * @method date_sub
 * @method date_timezone_get
 * @method date_timezone_set
 * @method date_offset_get
 * @method date_diff
 * @method date_time_set
 * @method date_date_set
 * @method date_isodate_set
 * @method date_timestamp_set
 * @method date_timestamp_get
 * @method timezone_open
 * @method timezone_name_get
 * @method timezone_name_from_abbr
 * @method timezone_offset_get
 * @method timezone_transitions_get
 * @method timezone_location_get
 * @method timezone_identifiers_list
 * @method timezone_abbreviations_list
 * @method timezone_version_get
 * @method date_interval_create_from_date_string
 * @method date_interval_format
 * @method date_default_timezone_set
 * @method date_default_timezone_get
 * @method date_sunrise
 * @method date_sunset
 * @method date_sun_info
 * @method ereg
 * @method ereg_replace
 * @method eregi
 * @method eregi_replace
 * @method split
 * @method spliti
 * @method sql_regcase
 * @method libxml_set_streams_context
 * @method libxml_use_internal_errors
 * @method libxml_get_last_error
 * @method libxml_clear_errors
 * @method libxml_get_errors
 * @method libxml_disable_entity_loader
 * @method libxml_set_external_entity_loader
 * @method openssl_get_cert_locations
 * @method openssl_spki_new
 * @method openssl_spki_verify
 * @method openssl_spki_export
 * @method openssl_spki_export_challenge
 * @method openssl_pkey_free
 * @method openssl_pkey_new
 * @method openssl_pkey_export
 * @method openssl_pkey_export_to_file
 * @method openssl_pkey_get_private
 * @method openssl_pkey_get_public
 * @method openssl_pkey_get_details
 * @method openssl_free_key
 * @method openssl_get_privatekey
 * @method openssl_get_publickey
 * @method openssl_x509_read
 * @method openssl_x509_free
 * @method openssl_x509_parse
 * @method openssl_x509_checkpurpose
 * @method openssl_x509_check_private_key
 * @method openssl_x509_export
 * @method openssl_x509_fingerprint
 * @method openssl_x509_export_to_file
 * @method openssl_pkcs12_export
 * @method openssl_pkcs12_export_to_file
 * @method openssl_pkcs12_read
 * @method openssl_csr_new
 * @method openssl_csr_export
 * @method openssl_csr_export_to_file
 * @method openssl_csr_sign
 * @method openssl_csr_get_subject
 * @method openssl_csr_get_public_key
 * @method openssl_digest
 * @method openssl_encrypt
 * @method openssl_decrypt
 * @method openssl_cipher_iv_length
 * @method openssl_sign
 * @method openssl_verify
 * @method openssl_seal
 * @method openssl_open
 * @method openssl_pbkdf2
 * @method openssl_pkcs7_verify
 * @method openssl_pkcs7_decrypt
 * @method openssl_pkcs7_sign
 * @method openssl_pkcs7_encrypt
 * @method openssl_private_encrypt
 * @method openssl_private_decrypt
 * @method openssl_public_encrypt
 * @method openssl_public_decrypt
 * @method openssl_get_md_methods
 * @method openssl_get_cipher_methods
 * @method openssl_dh_compute_key
 * @method openssl_random_pseudo_bytes
 * @method openssl_error_string
 * @method preg_match
 * @method preg_match_all
 * @method preg_replace
 * @method preg_replace_callback
 * @method preg_filter
 * @method preg_split
 * @method preg_quote
 * @method preg_grep
 * @method preg_last_error
 * @method readgzfile
 * @method gzrewind
 * @method gzclose
 * @method gzeof
 * @method gzgetc
 * @method gzgets
 * @method gzgetss
 * @method gzread
 * @method gzopen
 * @method gzpassthru
 * @method gzseek
 * @method gztell
 * @method gzwrite
 * @method gzputs
 * @method gzfile
 * @method gzcompress
 * @method gzuncompress
 * @method gzdeflate
 * @method gzinflate
 * @method gzencode
 * @method gzdecode
 * @method zlib_encode
 * @method zlib_decode
 * @method zlib_get_coding_type
 * @method ob_gzhandler
 * @method bcadd
 * @method bcsub
 * @method bcmul
 * @method bcdiv
 * @method bcmod
 * @method bcpow
 * @method bcsqrt
 * @method bcscale
 * @method bccomp
 * @method bcpowmod
 * @method bzopen
 * @method bzread
 * @method bzwrite
 * @method bzflush
 * @method bzclose
 * @method bzerrno
 * @method bzerrstr
 * @method bzerror
 * @method bzcompress
 * @method bzdecompress
 * @method jdtogregorian
 * @method gregoriantojd
 * @method jdtojulian
 * @method juliantojd
 * @method jdtojewish
 * @method jewishtojd
 * @method jdtofrench
 * @method frenchtojd
 * @method jddayofweek
 * @method jdmonthname
 * @method easter_date
 * @method easter_days
 * @method unixtojd
 * @method jdtounix
 * @method cal_to_jd
 * @method cal_from_jd
 * @method cal_days_in_month
 * @method cal_info
 * @method ctype_alnum
 * @method ctype_alpha
 * @method ctype_cntrl
 * @method ctype_digit
 * @method ctype_lower
 * @method ctype_graph
 * @method ctype_print
 * @method ctype_punct
 * @method ctype_space
 * @method ctype_upper
 * @method ctype_xdigit
 * @method curl_init
 * @method curl_copy_handle
 * @method curl_version
 * @method curl_setopt
 * @method curl_setopt_array
 * @method curl_exec
 * @method curl_getinfo
 * @method curl_error
 * @method curl_errno
 * @method curl_close
 * @method curl_strerror
 * @method curl_multi_strerror
 * @method curl_reset
 * @method curl_escape
 * @method curl_unescape
 * @method curl_pause
 * @method curl_multi_init
 * @method curl_multi_add_handle
 * @method curl_multi_remove_handle
 * @method curl_multi_select
 * @method curl_multi_exec
 * @method curl_multi_getcontent
 * @method curl_multi_info_read
 * @method curl_multi_close
 * @method curl_multi_setopt
 * @method curl_share_init
 * @method curl_share_close
 * @method curl_share_setopt
 * @method curl_file_create
 * @method dba_open
 * @method dba_popen
 * @method dba_close
 * @method dba_delete
 * @method dba_exists
 * @method dba_fetch
 * @method dba_insert
 * @method dba_replace
 * @method dba_firstkey
 * @method dba_nextkey
 * @method dba_optimize
 * @method dba_sync
 * @method dba_handlers
 * @method dba_list
 * @method dba_key_split
 * @method dom_import_simplexml
 * @method exif_read_data
 * @method read_exif_data
 * @method exif_tagname
 * @method exif_thumbnail
 * @method exif_imagetype
 * @method finfo_open
 * @method finfo_close
 * @method finfo_set_flags
 * @method finfo_file
 * @method finfo_buffer
 * @method mime_content_type
 * @method filter_input
 * @method filter_var
 * @method filter_input_array
 * @method filter_var_array
 * @method filter_list
 * @method filter_has_var
 * @method filter_id
 * @method ftp_connect
 * @method ftp_ssl_connect
 * @method ftp_login
 * @method ftp_pwd
 * @method ftp_cdup
 * @method ftp_chdir
 * @method ftp_exec
 * @method ftp_raw
 * @method ftp_mkdir
 * @method ftp_rmdir
 * @method ftp_chmod
 * @method ftp_alloc
 * @method ftp_nlist
 * @method ftp_rawlist
 * @method ftp_systype
 * @method ftp_pasv
 * @method ftp_get
 * @method ftp_fget
 * @method ftp_put
 * @method ftp_fput
 * @method ftp_size
 * @method ftp_mdtm
 * @method ftp_rename
 * @method ftp_delete
 * @method ftp_site
 * @method ftp_close
 * @method ftp_set_option
 * @method ftp_get_option
 * @method ftp_nb_fget
 * @method ftp_nb_get
 * @method ftp_nb_continue
 * @method ftp_nb_put
 * @method ftp_nb_fput
 * @method ftp_quit
 * @method gd_info
 * @method imagearc
 * @method imageellipse
 * @method imagechar
 * @method imagecharup
 * @method imagecolorat
 * @method imagecolorallocate
 * @method imagepalettecopy
 * @method imagecreatefromstring
 * @method imagecolorclosest
 * @method imagecolorclosesthwb
 * @method imagecolordeallocate
 * @method imagecolorresolve
 * @method imagecolorexact
 * @method imagecolorset
 * @method imagecolortransparent
 * @method imagecolorstotal
 * @method imagecolorsforindex
 * @method imagecopy
 * @method imagecopymerge
 * @method imagecopymergegray
 * @method imagecopyresized
 * @method imagecreate
 * @method imagecreatetruecolor
 * @method imageistruecolor
 * @method imagetruecolortopalette
 * @method imagepalettetotruecolor
 * @method imagesetthickness
 * @method imagefilledarc
 * @method imagefilledellipse
 * @method imagealphablending
 * @method imagesavealpha
 * @method imagecolorallocatealpha
 * @method imagecolorresolvealpha
 * @method imagecolorclosestalpha
 * @method imagecolorexactalpha
 * @method imagecopyresampled
 * @method imagerotate
 * @method imageflip
 * @method imageantialias
 * @method imagecrop
 * @method imagecropauto
 * @method imagescale
 * @method imageaffine
 * @method imageaffinematrixconcat
 * @method imageaffinematrixget
 * @method imagesetinterpolation
 * @method imagesettile
 * @method imagesetbrush
 * @method imagesetstyle
 * @method imagecreatefrompng
 * @method imagecreatefromgif
 * @method imagecreatefromjpeg
 * @method imagecreatefromwbmp
 * @method imagecreatefromxbm
 * @method imagecreatefromgd
 * @method imagecreatefromgd2
 * @method imagecreatefromgd2part
 * @method imagepng
 * @method imagegif
 * @method imagejpeg
 * @method imagewbmp
 * @method imagegd
 * @method imagegd2
 * @method imagedestroy
 * @method imagegammacorrect
 * @method imagefill
 * @method imagefilledpolygon
 * @method imagefilledrectangle
 * @method imagefilltoborder
 * @method imagefontwidth
 * @method imagefontheight
 * @method imageinterlace
 * @method imageline
 * @method imageloadfont
 * @method imagepolygon
 * @method imagerectangle
 * @method imagesetpixel
 * @method imagestring
 * @method imagestringup
 * @method imagesx
 * @method imagesy
 * @method imagedashedline
 * @method imagettfbbox
 * @method imagettftext
 * @method imageftbbox
 * @method imagefttext
 * @method imagetypes
 * @method jpeg2wbmp
 * @method png2wbmp
 * @method image2wbmp
 * @method imagelayereffect
 * @method imagexbm
 * @method imagecolormatch
 * @method imagefilter
 * @method imageconvolution
 * @method textdomain
 * @method gettext
 * @method _
 * @method dgettext
 * @method dcgettext
 * @method bindtextdomain
 * @method ngettext
 * @method dngettext
 * @method dcngettext
 * @method bind_textdomain_codeset
 * @method hash
 * @method hash_file
 * @method hash_hmac
 * @method hash_hmac_file
 * @method hash_init
 * @method hash_update
 * @method hash_update_stream
 * @method hash_update_file
 * @method hash_final
 * @method hash_copy
 * @method hash_algos
 * @method hash_pbkdf2
 * @method hash_equals
 * @method mhash_keygen_s2k
 * @method mhash_get_block_size
 * @method mhash_get_hash_name
 * @method mhash_count
 * @method mhash
 * @method iconv
 * @method iconv_get_encoding
 * @method iconv_set_encoding
 * @method iconv_strlen
 * @method iconv_substr
 * @method iconv_strpos
 * @method iconv_strrpos
 * @method iconv_mime_encode
 * @method iconv_mime_decode
 * @method iconv_mime_decode_headers
 * @method json_encode (mixed $value, int $options = 0, int $depth = 512)
 * @method json_decode (string $json, bool $assoc = false, int $depth = 512, int $options = 0)
 * @method json_last_error
 * @method json_last_error_msg
 * @method ldap_connect
 * @method ldap_close
 * @method ldap_bind
 * @method ldap_sasl_bind
 * @method ldap_unbind
 * @method ldap_read
 * @method ldap_list
 * @method ldap_search
 * @method ldap_free_result
 * @method ldap_count_entries
 * @method ldap_first_entry
 * @method ldap_next_entry
 * @method ldap_get_entries
 * @method ldap_first_attribute
 * @method ldap_next_attribute
 * @method ldap_get_attributes
 * @method ldap_get_values
 * @method ldap_get_values_len
 * @method ldap_get_dn
 * @method ldap_explode_dn
 * @method ldap_dn2ufn
 * @method ldap_add
 * @method ldap_delete
 * @method ldap_modify_batch
 * @method ldap_modify
 * @method ldap_mod_add
 * @method ldap_mod_replace
 * @method ldap_mod_del
 * @method ldap_errno
 * @method ldap_err2str
 * @method ldap_error
 * @method ldap_compare
 * @method ldap_sort
 * @method ldap_rename
 * @method ldap_get_option
 * @method ldap_set_option
 * @method ldap_first_reference
 * @method ldap_next_reference
 * @method ldap_parse_reference
 * @method ldap_parse_result
 * @method ldap_start_tls
 * @method ldap_set_rebind_proc
 * @method ldap_escape
 * @method ldap_control_paged_result
 * @method ldap_control_paged_result_response
 * @method mb_convert_case
 * @method mb_strtoupper
 * @method mb_strtolower
 * @method mb_language
 * @method mb_internal_encoding
 * @method mb_http_input
 * @method mb_http_output
 * @method mb_detect_order
 * @method mb_substitute_character
 * @method mb_parse_str
 * @method mb_output_handler
 * @method mb_preferred_mime_name
 * @method mb_strlen
 * @method mb_strpos
 * @method mb_strrpos
 * @method mb_stripos
 * @method mb_strripos
 * @method mb_strstr
 * @method mb_strrchr
 * @method mb_stristr
 * @method mb_strrichr
 * @method mb_substr_count
 * @method mb_substr
 * @method mb_strcut
 * @method mb_strwidth
 * @method mb_strimwidth
 * @method mb_convert_encoding
 * @method mb_detect_encoding
 * @method mb_list_encodings
 * @method mb_encoding_aliases
 * @method mb_convert_kana
 * @method mb_encode_mimeheader
 * @method mb_decode_mimeheader
 * @method mb_convert_variables
 * @method mb_encode_numericentity
 * @method mb_decode_numericentity
 * @method mb_send_mail
 * @method mb_get_info
 * @method mb_check_encoding
 * @method mb_regex_encoding
 * @method mb_regex_set_options
 * @method mb_ereg
 * @method mb_eregi
 * @method mb_ereg_replace
 * @method mb_eregi_replace
 * @method mb_ereg_replace_callback
 * @method mb_split
 * @method mb_ereg_match
 * @method mb_ereg_search
 * @method mb_ereg_search_pos
 * @method mb_ereg_search_regs
 * @method mb_ereg_search_init
 * @method mb_ereg_search_getregs
 * @method mb_ereg_search_getpos
 * @method mb_ereg_search_setpos
 * @method mbregex_encoding
 * @method mbereg
 * @method mberegi
 * @method mbereg_replace
 * @method mberegi_replace
 * @method mbsplit
 * @method mbereg_match
 * @method mbereg_search
 * @method mbereg_search_pos
 * @method mbereg_search_regs
 * @method mbereg_search_init
 * @method mbereg_search_getregs
 * @method mbereg_search_getpos
 * @method mbereg_search_setpos
 * @method mysql_connect
 * @method mysql_pconnect
 * @method mysql_close
 * @method mysql_select_db
 * @method mysql_query
 * @method mysql_unbuffered_query
 * @method mysql_db_query
 * @method mysql_list_dbs
 * @method mysql_list_tables
 * @method mysql_list_fields
 * @method mysql_list_processes
 * @method mysql_error
 * @method mysql_errno
 * @method mysql_affected_rows
 * @method mysql_insert_id
 * @method mysql_result
 * @method mysql_num_rows
 * @method mysql_num_fields
 * @method mysql_fetch_row
 * @method mysql_fetch_array
 * @method mysql_fetch_assoc
 * @method mysql_fetch_object
 * @method mysql_data_seek
 * @method mysql_fetch_lengths
 * @method mysql_fetch_field
 * @method mysql_field_seek
 * @method mysql_free_result
 * @method mysql_field_name
 * @method mysql_field_table
 * @method mysql_field_len
 * @method mysql_field_type
 * @method mysql_field_flags
 * @method mysql_escape_string
 * @method mysql_real_escape_string
 * @method mysql_stat
 * @method mysql_thread_id
 * @method mysql_client_encoding
 * @method mysql_ping
 * @method mysql_get_client_info
 * @method mysql_get_host_info
 * @method mysql_get_proto_info
 * @method mysql_get_server_info
 * @method mysql_info
 * @method mysql_set_charset
 * @method mysql
 * @method mysql_fieldname
 * @method mysql_fieldtable
 * @method mysql_fieldlen
 * @method mysql_fieldtype
 * @method mysql_fieldflags
 * @method mysql_selectdb
 * @method mysql_freeresult
 * @method mysql_numfields
 * @method mysql_numrows
 * @method mysql_listdbs
 * @method mysql_listtables
 * @method mysql_listfields
 * @method mysql_db_name
 * @method mysql_dbname
 * @method mysql_tablename
 * @method mysql_table_name
 * @method mysqli_affected_rows
 * @method mysqli_autocommit
 * @method mysqli_begin_transaction
 * @method mysqli_change_user
 * @method mysqli_character_set_name
 * @method mysqli_close
 * @method mysqli_commit
 * @method mysqli_connect
 * @method mysqli_connect_errno
 * @method mysqli_connect_error
 * @method mysqli_data_seek
 * @method mysqli_dump_debug_info
 * @method mysqli_debug
 * @method mysqli_errno
 * @method mysqli_error
 * @method mysqli_error_list
 * @method mysqli_stmt_execute
 * @method mysqli_execute
 * @method mysqli_fetch_field
 * @method mysqli_fetch_fields
 * @method mysqli_fetch_field_direct
 * @method mysqli_fetch_lengths
 * @method mysqli_fetch_all
 * @method mysqli_fetch_array
 * @method mysqli_fetch_assoc
 * @method mysqli_fetch_object
 * @method mysqli_fetch_row
 * @method mysqli_field_count
 * @method mysqli_field_seek
 * @method mysqli_field_tell
 * @method mysqli_free_result
 * @method mysqli_get_connection_stats
 * @method mysqli_get_client_stats
 * @method mysqli_get_charset
 * @method mysqli_get_client_info
 * @method mysqli_get_client_version
 * @method mysqli_get_links_stats
 * @method mysqli_get_host_info
 * @method mysqli_get_proto_info
 * @method mysqli_get_server_info
 * @method mysqli_get_server_version
 * @method mysqli_get_warnings
 * @method mysqli_init
 * @method mysqli_info
 * @method mysqli_insert_id
 * @method mysqli_kill
 * @method mysqli_more_results
 * @method mysqli_multi_query
 * @method mysqli_next_result
 * @method mysqli_num_fields
 * @method mysqli_num_rows
 * @method mysqli_options
 * @method mysqli_ping
 * @method mysqli_poll
 * @method mysqli_prepare
 * @method mysqli_report
 * @method mysqli_query
 * @method mysqli_real_connect
 * @method mysqli_real_escape_string
 * @method mysqli_real_query
 * @method mysqli_reap_async_query
 * @method mysqli_release_savepoint
 * @method mysqli_rollback
 * @method mysqli_savepoint
 * @method mysqli_select_db
 * @method mysqli_set_charset
 * @method mysqli_stmt_affected_rows
 * @method mysqli_stmt_attr_get
 * @method mysqli_stmt_attr_set
 * @method mysqli_stmt_bind_param
 * @method mysqli_stmt_bind_result
 * @method mysqli_stmt_close
 * @method mysqli_stmt_data_seek
 * @method mysqli_stmt_errno
 * @method mysqli_stmt_error
 * @method mysqli_stmt_error_list
 * @method mysqli_stmt_fetch
 * @method mysqli_stmt_field_count
 * @method mysqli_stmt_free_result
 * @method mysqli_stmt_get_result
 * @method mysqli_stmt_get_warnings
 * @method mysqli_stmt_init
 * @method mysqli_stmt_insert_id
 * @method mysqli_stmt_more_results
 * @method mysqli_stmt_next_result
 * @method mysqli_stmt_num_rows
 * @method mysqli_stmt_param_count
 * @method mysqli_stmt_prepare
 * @method mysqli_stmt_reset
 * @method mysqli_stmt_result_metadata
 * @method mysqli_stmt_send_long_data
 * @method mysqli_stmt_store_result
 * @method mysqli_stmt_sqlstate
 * @method mysqli_sqlstate
 * @method mysqli_ssl_set
 * @method mysqli_stat
 * @method mysqli_store_result
 * @method mysqli_thread_id
 * @method mysqli_thread_safe
 * @method mysqli_use_result
 * @method mysqli_warning_count
 * @method mysqli_refresh
 * @method mysqli_escape_string
 * @method mysqli_set_opt
 * @method odbc_autocommit
 * @method odbc_binmode
 * @method odbc_close
 * @method odbc_close_all
 * @method odbc_columns
 * @method odbc_commit
 * @method odbc_connect
 * @method odbc_cursor
 * @method odbc_data_source
 * @method odbc_execute
 * @method odbc_error
 * @method odbc_errormsg
 * @method odbc_exec
 * @method odbc_fetch_array
 * @method odbc_fetch_object
 * @method odbc_fetch_row
 * @method odbc_fetch_into
 * @method odbc_field_len
 * @method odbc_field_scale
 * @method odbc_field_name
 * @method odbc_field_type
 * @method odbc_field_num
 * @method odbc_free_result
 * @method odbc_gettypeinfo
 * @method odbc_longreadlen
 * @method odbc_next_result
 * @method odbc_num_fields
 * @method odbc_num_rows
 * @method odbc_pconnect
 * @method odbc_prepare
 * @method odbc_result
 * @method odbc_result_all
 * @method odbc_rollback
 * @method odbc_setoption
 * @method odbc_specialcolumns
 * @method odbc_statistics
 * @method odbc_tables
 * @method odbc_primarykeys
 * @method odbc_columnprivileges
 * @method odbc_tableprivileges
 * @method odbc_foreignkeys
 * @method odbc_procedures
 * @method odbc_procedurecolumns
 * @method odbc_do
 * @method odbc_field_precision
 * @method pcntl_fork
 * @method pcntl_waitpid
 * @method pcntl_wait
 * @method pcntl_signal
 * @method pcntl_signal_dispatch
 * @method pcntl_wifexited
 * @method pcntl_wifstopped
 * @method pcntl_wifsignaled
 * @method pcntl_wexitstatus
 * @method pcntl_wtermsig
 * @method pcntl_wstopsig
 * @method pcntl_exec
 * @method pcntl_alarm
 * @method pcntl_get_last_error
 * @method pcntl_errno
 * @method pcntl_strerror
 * @method pcntl_getpriority
 * @method pcntl_setpriority
 * @method pcntl_sigprocmask
 * @method spl_classes
 * @method spl_autoload
 * @method spl_autoload_extensions
 * @method spl_autoload_register
 * @method spl_autoload_unregister
 * @method spl_autoload_functions
 * @method spl_autoload_call
 * @method class_parents
 * @method class_implements
 * @method class_uses
 * @method spl_object_hash
 * @method iterator_to_array
 * @method iterator_count
 * @method iterator_apply
 * @method pdo_drivers
 * @method posix_kill
 * @method posix_getpid
 * @method posix_getppid
 * @method posix_getuid
 * @method posix_setuid
 * @method posix_geteuid
 * @method posix_seteuid
 * @method posix_getgid
 * @method posix_setgid
 * @method posix_getegid
 * @method posix_setegid
 * @method posix_getgroups
 * @method posix_getlogin
 * @method posix_getpgrp
 * @method posix_setsid
 * @method posix_setpgid
 * @method posix_getpgid
 * @method posix_getsid
 * @method posix_uname
 * @method posix_times
 * @method posix_ctermid
 * @method posix_ttyname
 * @method posix_isatty
 * @method posix_getcwd
 * @method posix_mkfifo
 * @method posix_mknod
 * @method posix_access
 * @method posix_getgrnam
 * @method posix_getgrgid
 * @method posix_getpwnam
 * @method posix_getpwuid
 * @method posix_getrlimit
 * @method posix_get_last_error
 * @method posix_errno
 * @method posix_strerror
 * @method posix_initgroups
 * @method readline
 * @method readline_info
 * @method readline_add_history
 * @method readline_clear_history
 * @method readline_read_history
 * @method readline_write_history
 * @method readline_completion_function
 * @method readline_callback_handler_install
 * @method readline_callback_read_char
 * @method readline_callback_handler_remove
 * @method readline_redisplay
 * @method readline_on_new_line
 * @method session_name
 * @method session_module_name
 * @method session_save_path
 * @method session_id
 * @method session_regenerate_id
 * @method session_decode
 * @method session_encode
 * @method session_start
 * @method session_destroy
 * @method session_unset
 * @method session_set_save_handler
 * @method session_cache_limiter
 * @method session_cache_expire
 * @method session_set_cookie_params
 * @method session_get_cookie_params
 * @method session_write_close
 * @method session_abort
 * @method session_reset
 * @method session_status
 * @method session_register_shutdown
 * @method session_commit
 * @method shmop_open
 * @method shmop_read
 * @method shmop_close
 * @method shmop_size
 * @method shmop_write
 * @method shmop_delete
 * @method simplexml_load_file
 * @method simplexml_load_string
 * @method simplexml_import_dom
 * @method use_soap_error_handler
 * @method is_soap_fault
 * @method socket_select
 * @method socket_create
 * @method socket_create_listen
 * @method socket_create_pair
 * @method socket_accept
 * @method socket_set_nonblock
 * @method socket_set_block
 * @method socket_listen
 * @method socket_close
 * @method socket_write
 * @method socket_read
 * @method socket_getsockname
 * @method socket_getpeername
 * @method socket_connect
 * @method socket_strerror
 * @method socket_bind
 * @method socket_recv
 * @method socket_send
 * @method socket_recvfrom
 * @method socket_sendto
 * @method socket_get_option
 * @method socket_set_option
 * @method socket_shutdown
 * @method socket_last_error
 * @method socket_clear_error
 * @method socket_import_stream
 * @method socket_sendmsg
 * @method socket_recvmsg
 * @method socket_cmsg_space
 * @method socket_getopt
 * @method socket_setopt
 * @method constant
 * @method bin2hex
 * @method hex2bin
 * @method sleep
 * @method usleep
 * @method time_nanosleep
 * @method time_sleep_until
 * @method strptime
 * @method flush
 * @method wordwrap
 * @method htmlspecialchars
 * @method htmlentities
 * @method html_entity_decode
 * @method htmlspecialchars_decode
 * @method get_html_translation_table
 * @method sha1
 * @method sha1_file
 * @method md5
 * @method md5_file
 * @method crc32
 * @method iptcparse
 * @method iptcembed
 * @method getimagesize
 * @method getimagesizefromstring
 * @method image_type_to_mime_type
 * @method image_type_to_extension
 * @method phpinfo
 * @method phpversion
 * @method phpcredits
 * @method php_sapi_name
 * @method php_uname
 * @method php_ini_scanned_files
 * @method php_ini_loaded_file
 * @method strnatcmp
 * @method strnatcasecmp
 * @method substr_count
 * @method strspn
 * @method strcspn
 * @method strtok
 * @method strtoupper
 * @method strtolower
 * @method strpos
 * @method stripos
 * @method strrpos
 * @method strripos
 * @method strrev
 * @method hebrev
 * @method hebrevc
 * @method nl2br
 * @method basename
 * @method dirname
 * @method pathinfo
 * @method stripslashes
 * @method stripcslashes
 * @method strstr
 * @method stristr
 * @method strrchr
 * @method str_shuffle
 * @method str_word_count
 * @method str_split
 * @method strpbrk
 * @method substr_compare
 * @method strcoll
 * @method money_format
 * @method substr
 * @method substr_replace
 * @method quotemeta
 * @method ucfirst
 * @method lcfirst
 * @method ucwords
 * @method strtr
 * @method addslashes
 * @method addcslashes
 * @method rtrim
 * @method str_replace
 * @method str_ireplace
 * @method str_repeat
 * @method count_chars
 * @method chunk_split
 * @method trim
 * @method ltrim
 * @method strip_tags
 * @method similar_text
 * @method explode
 * @method implode
 * @method join
 * @method setlocale
 * @method localeconv
 * @method nl_langinfo
 * @method soundex
 * @method levenshtein
 * @method chr
 * @method ord
 * @method parse_str
 * @method str_getcsv
 * @method str_pad
 * @method chop
 * @method strchr
 * @method sprintf
 * @method printf
 * @method vprintf
 * @method vsprintf
 * @method fprintf
 * @method vfprintf
 * @method sscanf
 * @method fscanf
 * @method parse_url
 * @method urlencode
 * @method urldecode
 * @method rawurlencode
 * @method rawurldecode
 * @method http_build_query
 * @method readlink
 * @method linkinfo
 * @method symlink
 * @method link
 * @method unlink
 * @method exec
 * @method system
 * @method escapeshellcmd
 * @method escapeshellarg
 * @method passthru
 * @method shell_exec
 * @method proc_open
 * @method proc_close
 * @method proc_terminate
 * @method proc_get_status
 * @method proc_nice
 * @method rand
 * @method srand
 * @method getrandmax
 * @method mt_rand
 * @method mt_srand
 * @method mt_getrandmax
 * @method getservbyname
 * @method getservbyport
 * @method getprotobyname
 * @method getprotobynumber
 * @method getmyuid
 * @method getmygid
 * @method getmypid
 * @method getmyinode
 * @method getlastmod
 * @method base64_decode
 * @method base64_encode
 * @method password_hash
 * @method password_get_info
 * @method password_needs_rehash
 * @method password_verify
 * @method convert_uuencode
 * @method convert_uudecode
 * @method abs
 * @method ceil
 * @method floor
 * @method round
 * @method sin
 * @method cos
 * @method tan
 * @method asin
 * @method acos
 * @method atan
 * @method atanh
 * @method atan2
 * @method sinh
 * @method cosh
 * @method tanh
 * @method asinh
 * @method acosh
 * @method expm1
 * @method log1p
 * @method pi
 * @method is_finite
 * @method is_nan
 * @method is_infinite
 * @method pow
 * @method exp
 * @method log
 * @method log10
 * @method sqrt
 * @method hypot
 * @method deg2rad
 * @method rad2deg
 * @method bindec
 * @method hexdec
 * @method octdec
 * @method decbin
 * @method decoct
 * @method dechex
 * @method base_convert
 * @method number_format
 * @method fmod
 * @method inet_ntop
 * @method inet_pton
 * @method ip2long
 * @method long2ip
 * @method getenv
 * @method putenv
 * @method getopt
 * @method sys_getloadavg
 * @method microtime
 * @method gettimeofday
 * @method getrusage
 * @method uniqid
 * @method quoted_printable_decode
 * @method quoted_printable_encode
 * @method convert_cyr_string
 * @method get_current_user
 * @method set_time_limit
 * @method header_register_callback
 * @method get_cfg_var
 * @method magic_quotes_runtime
 * @method set_magic_quotes_runtime
 * @method get_magic_quotes_gpc
 * @method get_magic_quotes_runtime
 * @method error_log
 * @method error_get_last
 * @method call_user_func
 * @method call_user_func_array
 * @method call_user_method
 * @method call_user_method_array
 * @method forward_static_call
 * @method forward_static_call_array
 * @method serialize
 * @method unserialize
 * @method var_dump
 * @method var_export
 * @method debug_zval_dump
 * @method print_r
 * @method memory_get_usage
 * @method memory_get_peak_usage
 * @method register_shutdown_function
 * @method register_tick_function
 * @method unregister_tick_function
 * @method highlight_file
 * @method show_source
 * @method highlight_string
 * @method php_strip_whitespace
 * @method ini_get
 * @method ini_get_all
 * @method ini_set
 * @method ini_alter
 * @method ini_restore
 * @method get_include_path
 * @method set_include_path
 * @method restore_include_path
 * @method setcookie
 * @method setrawcookie
 * @method header
 * @method header_remove
 * @method headers_sent
 * @method headers_list
 * @method http_response_code
 * @method connection_aborted
 * @method connection_status
 * @method ignore_user_abort
 * @method parse_ini_file
 * @method parse_ini_string
 * @method is_uploaded_file
 * @method move_uploaded_file
 * @method gethostbyaddr
 * @method gethostbyname
 * @method gethostbynamel
 * @method gethostname
 * @method dns_check_record
 * @method checkdnsrr
 * @method dns_get_mx
 * @method getmxrr
 * @method dns_get_record
 * @method intval
 * @method floatval
 * @method doubleval
 * @method strval
 * @method boolval
 * @method gettype
 * @method settype
 * @method is_null
 * @method is_resource
 * @method is_bool
 * @method is_long
 * @method is_float
 * @method is_int
 * @method is_integer
 * @method is_double
 * @method is_real
 * @method is_numeric
 * @method is_string
 * @method is_array
 * @method is_object (mixed $var)
 * @method is_scalar
 * @method is_callable(mixed $var, bool $syntax_only = false, string &$callable_name = '')
 * @method pclose
 * @method popen
 * @method readfile
 * @method rewind
 * @method rmdir
 * @method umask
 * @method fclose
 * @method feof
 * @method fgetc
 * @method fgets
 * @method fgetss
 * @method fread
 * @method fopen
 * @method fpassthru
 * @method ftruncate
 * @method fstat
 * @method fseek
 * @method ftell
 * @method fflush
 * @method fwrite (resource $handle, string $string, int $length = 0)
 * @method fputs
 * @method mkdir
 * @method rename
 * @method copy
 * @method tempnam
 * @method tmpfile
 * @method file
 * @method file_get_contents (string $filename, bool $use_include_path = false, resource $context = null, int $offset = 0, int $maxlen = 0)
 * @method file_put_contents (string $filename, mixed $content)
 * @method stream_select
 * @method stream_context_create
 * @method stream_context_set_params
 * @method stream_context_get_params
 * @method stream_context_set_option
 * @method stream_context_get_options
 * @method stream_context_get_default
 * @method stream_context_set_default
 * @method stream_filter_prepend
 * @method stream_filter_append
 * @method stream_filter_remove
 * @method stream_socket_client
 * @method stream_socket_server
 * @method stream_socket_accept
 * @method stream_socket_get_name
 * @method stream_socket_recvfrom
 * @method stream_socket_sendto
 * @method stream_socket_enable_crypto
 * @method stream_socket_shutdown
 * @method stream_socket_pair
 * @method stream_copy_to_stream
 * @method stream_get_contents
 * @method stream_supports_lock
 * @method fgetcsv
 * @method fputcsv
 * @method flock
 * @method get_meta_tags
 * @method stream_set_read_buffer
 * @method stream_set_write_buffer
 * @method set_file_buffer
 * @method stream_set_chunk_size
 * @method set_socket_blocking
 * @method stream_set_blocking
 * @method socket_set_blocking
 * @method stream_get_meta_data
 * @method stream_get_line
 * @method stream_wrapper_register
 * @method stream_register_wrapper
 * @method stream_wrapper_unregister
 * @method stream_wrapper_restore
 * @method stream_get_wrappers
 * @method stream_get_transports
 * @method stream_resolve_include_path
 * @method stream_is_local
 * @method get_headers
 * @method stream_set_timeout
 * @method socket_set_timeout
 * @method socket_get_status
 * @method realpath
 * @method fnmatch
 * @method fsockopen
 * @method pfsockopen
 * @method pack
 * @method unpack
 * @method get_browser
 * @method crypt
 * @method opendir
 * @method closedir
 * @method chdir
 * @method getcwd
 * @method rewinddir
 * @method readdir
 * @method dir
 * @method scandir
 * @method glob
 * @method fileatime
 * @method filectime
 * @method filegroup
 * @method fileinode
 * @method filemtime
 * @method fileowner
 * @method fileperms
 * @method filesize
 * @method filetype
 * @method file_exists ($filename)
 * @method is_writable
 * @method is_writeable
 * @method is_readable
 * @method is_executable
 * @method is_file
 * @method is_dir
 * @method is_link
 * @method stat
 * @method lstat
 * @method chown
 * @method chgrp
 * @method lchown
 * @method lchgrp
 * @method chmod
 * @method touch
 * @method clearstatcache
 * @method disk_total_space
 * @method disk_free_space
 * @method diskfreespace
 * @method realpath_cache_size
 * @method realpath_cache_get
 * @method mail
 * @method ezmlm_hash
 * @method openlog
 * @method syslog
 * @method closelog
 * @method lcg_value
 * @method metaphone
 * @method ob_start
 * @method ob_flush
 * @method ob_clean
 * @method ob_end_flush
 * @method ob_end_clean
 * @method ob_get_flush
 * @method ob_get_clean
 * @method ob_get_length
 * @method ob_get_level
 * @method ob_get_status
 * @method ob_get_contents
 * @method ob_implicit_flush
 * @method ob_list_handlers
 * @method ksort
 * @method krsort
 * @method natsort
 * @method natcasesort
 * @method asort
 * @method arsort
 * @method sort
 * @method rsort
 * @method usort
 * @method uasort
 * @method uksort
 * @method shuffle
 * @method array_walk
 * @method array_walk_recursive
 * @method count
 * @method end
 * @method prev
 * @method next
 * @method reset
 * @method current
 * @method key
 * @method min
 * @method max
 * @method in_array
 * @method array_search
 * @method extract
 * @method compact
 * @method array_fill
 * @method array_fill_keys
 * @method range
 * @method array_multisort
 * @method array_push
 * @method array_pop
 * @method array_shift
 * @method array_unshift
 * @method array_splice
 * @method array_slice
 * @method array_merge
 * @method array_merge_recursive ( array $array1, array $array2 = array() )
 * @method array_replace
 * @method array_replace_recursive
 * @method array_keys (array $array, mixed $search_value = null, bool $strict = false)
 * @method array_values
 * @method array_count_values
 * @method array_column
 * @method array_reverse
 * @method array_reduce
 * @method array_pad
 * @method array_flip
 * @method array_change_key_case
 * @method array_rand
 * @method array_unique
 * @method array_intersect
 * @method array_intersect_key
 * @method array_intersect_ukey
 * @method array_uintersect
 * @method array_intersect_assoc
 * @method array_uintersect_assoc
 * @method array_intersect_uassoc
 * @method array_uintersect_uassoc
 * @method array_diff
 * @method array_diff_key
 * @method array_diff_ukey
 * @method array_udiff
 * @method array_diff_assoc
 * @method array_udiff_assoc
 * @method array_diff_uassoc
 * @method array_udiff_uassoc
 * @method array_sum
 * @method array_product
 * @method array_filter
 * @method array_map
 * @method array_chunk
 * @method array_combine
 * @method array_key_exists
 * @method pos
 * @method sizeof
 * @method key_exists
 * @method assert
 * @method assert_options
 * @method version_compare(string $version1, string $version2, string $operator = null)
 * @method ftok
 * @method str_rot13
 * @method stream_get_filters
 * @method stream_filter_register
 * @method stream_bucket_make_writeable
 * @method stream_bucket_prepend
 * @method stream_bucket_append
 * @method stream_bucket_new
 * @method output_add_rewrite_var
 * @method output_reset_rewrite_vars
 * @method sys_get_temp_dir
 * @method msg_get_queue
 * @method msg_send
 * @method msg_receive
 * @method msg_remove_queue
 * @method msg_stat_queue
 * @method msg_set_queue
 * @method msg_queue_exists
 * @method sem_get
 * @method sem_acquire
 * @method sem_release
 * @method sem_remove
 * @method shm_attach
 * @method shm_remove
 * @method shm_detach
 * @method shm_put_var
 * @method shm_has_var
 * @method shm_get_var
 * @method shm_remove_var
 * @method token_get_all
 * @method token_name
 * @method wddx_serialize_value
 * @method wddx_serialize_vars
 * @method wddx_packet_start
 * @method wddx_packet_end
 * @method wddx_add_vars
 * @method wddx_deserialize
 * @method xml_parser_create
 * @method xml_parser_create_ns
 * @method xml_set_object
 * @method xml_set_element_handler
 * @method xml_set_character_data_handler
 * @method xml_set_processing_instruction_handler
 * @method xml_set_default_handler
 * @method xml_set_unparsed_entity_decl_handler
 * @method xml_set_notation_decl_handler
 * @method xml_set_external_entity_ref_handler
 * @method xml_set_start_namespace_decl_handler
 * @method xml_set_end_namespace_decl_handler
 * @method xml_parse
 * @method xml_parse_into_struct
 * @method xml_get_error_code
 * @method xml_error_string
 * @method xml_get_current_line_number
 * @method xml_get_current_column_number
 * @method xml_get_current_byte_index
 * @method xml_parser_free
 * @method xml_parser_set_option
 * @method xml_parser_get_option
 * @method utf8_encode
 * @method utf8_decode
 * @method xmlrpc_encode
 * @method xmlrpc_decode
 * @method xmlrpc_decode_request
 * @method xmlrpc_encode_request
 * @method xmlrpc_get_type
 * @method xmlrpc_set_type
 * @method xmlrpc_is_fault
 * @method xmlrpc_server_create
 * @method xmlrpc_server_destroy
 * @method xmlrpc_server_register_method
 * @method xmlrpc_server_call_method
 * @method xmlrpc_parse_method_descriptions
 * @method xmlrpc_server_add_introspection_data
 * @method xmlrpc_server_register_introspection_callback
 * @method xmlwriter_open_uri
 * @method xmlwriter_open_memory
 * @method xmlwriter_set_indent
 * @method xmlwriter_set_indent_string
 * @method xmlwriter_start_comment
 * @method xmlwriter_end_comment
 * @method xmlwriter_start_attribute
 * @method xmlwriter_end_attribute
 * @method xmlwriter_write_attribute
 * @method xmlwriter_start_attribute_ns
 * @method xmlwriter_write_attribute_ns
 * @method xmlwriter_start_element
 * @method xmlwriter_end_element
 * @method xmlwriter_full_end_element
 * @method xmlwriter_start_element_ns
 * @method xmlwriter_write_element
 * @method xmlwriter_write_element_ns
 * @method xmlwriter_start_pi
 * @method xmlwriter_end_pi
 * @method xmlwriter_write_pi
 * @method xmlwriter_start_cdata
 * @method xmlwriter_end_cdata
 * @method xmlwriter_write_cdata
 * @method xmlwriter_text
 * @method xmlwriter_write_raw
 * @method xmlwriter_start_document
 * @method xmlwriter_end_document
 * @method xmlwriter_write_comment
 * @method xmlwriter_start_dtd
 * @method xmlwriter_end_dtd
 * @method xmlwriter_write_dtd
 * @method xmlwriter_start_dtd_element
 * @method xmlwriter_end_dtd_element
 * @method xmlwriter_write_dtd_element
 * @method xmlwriter_start_dtd_attlist
 * @method xmlwriter_end_dtd_attlist
 * @method xmlwriter_write_dtd_attlist
 * @method xmlwriter_start_dtd_entity
 * @method xmlwriter_end_dtd_entity
 * @method xmlwriter_write_dtd_entity
 * @method xmlwriter_output_memory
 * @method xmlwriter_flush
 * @method zip_open
 * @method zip_close
 * @method zip_read
 * @method zip_entry_open
 * @method zip_entry_close
 * @method zip_entry_read
 * @method zip_entry_filesize
 * @method zip_entry_name
 * @method zip_entry_compressedsize
 * @method zip_entry_compressionmethod
 * @method mcrypt_ecb
 * @method mcrypt_cbc
 * @method mcrypt_cfb
 * @method mcrypt_ofb
 * @method mcrypt_get_key_size
 * @method mcrypt_get_block_size
 * @method mcrypt_get_cipher_name
 * @method mcrypt_create_iv
 * @method mcrypt_list_algorithms
 * @method mcrypt_list_modes
 * @method mcrypt_get_iv_size
 * @method mcrypt_encrypt
 * @method mcrypt_decrypt
 * @method mcrypt_module_open
 * @method mcrypt_generic_init
 * @method mcrypt_generic
 * @method mdecrypt_generic
 * @method mcrypt_generic_end
 * @method mcrypt_generic_deinit
 * @method mcrypt_enc_self_test
 * @method mcrypt_enc_is_block_algorithm_mode
 * @method mcrypt_enc_is_block_algorithm
 * @method mcrypt_enc_is_block_mode
 * @method mcrypt_enc_get_block_size
 * @method mcrypt_enc_get_key_size
 * @method mcrypt_enc_get_supported_key_sizes
 * @method mcrypt_enc_get_iv_size
 * @method mcrypt_enc_get_algorithms_name
 * @method mcrypt_enc_get_modes_name
 * @method mcrypt_module_self_test
 * @method mcrypt_module_is_block_algorithm_mode
 * @method mcrypt_module_is_block_algorithm
 * @method mcrypt_module_is_block_mode
 * @method mcrypt_module_get_algo_block_size
 * @method mcrypt_module_get_algo_key_size
 * @method mcrypt_module_get_supported_key_sizes
 * @method mcrypt_module_close
 * @method xdebug_get_stack_depth
 * @method xdebug_get_function_stack
 * @method xdebug_get_formatted_function_stack
 * @method xdebug_print_function_stack
 * @method xdebug_get_declared_vars
 * @method xdebug_call_class
 * @method xdebug_call_function
 * @method xdebug_call_file
 * @method xdebug_call_line
 * @method xdebug_var_dump
 * @method xdebug_debug_zval
 * @method xdebug_debug_zval_stdout
 * @method xdebug_enable
 * @method xdebug_disable
 * @method xdebug_is_enabled
 * @method xdebug_break
 * @method xdebug_start_trace
 * @method xdebug_stop_trace
 * @method xdebug_get_tracefile_name
 * @method xdebug_get_profiler_filename
 * @method xdebug_dump_aggr_profiling_data
 * @method xdebug_clear_aggr_profiling_data
 * @method xdebug_memory_usage
 * @method xdebug_peak_memory_usage
 * @method xdebug_time_index
 * @method xdebug_start_error_collection
 * @method xdebug_stop_error_collection
 * @method xdebug_get_collected_errors
 * @method xdebug_start_code_coverage
 * @method xdebug_stop_code_coverage
 * @method xdebug_get_code_coverage
 * @method xdebug_code_coverage_started
 * @method xdebug_get_function_count
 * @method xdebug_dump_superglobals
 * @method xdebug_get_headers
 * @method dl
 * @method cli_set_process_title
 * @method cli_get_process_title
 */
class Php
{
    /**
     * Wraps php functions
     *
     * called the php function
     *
     * @param $function
     * @param $args
     *
     * @return mixed
     * @throws \Exception
     */
    public function __call($function, $args)
    {
        if (in_array($function, get_defined_functions()['internal'])) {
            return call_user_func_array($function, $args);
        }

        throw new \Exception('call undefined function "'.$function.'"');
    }
}

